{{/*
Copyright IBM Corp. 2023, 2025
SPDX-License-Identifier: MPL-2.0
*/}}

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-tfe-data
  namespace: {{ .Release.Namespace }}
  labels:
    app: terraform-enterprise
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storageSize | default "100Gi" }}
